packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@fhenixprotocol/cofhe-contracts': set this to true or false
  bufferutil: false
  keccak: false
  secp256k1: set this to true or false
  sharp: true
  utf-8-validate: false
overrides:
  postcss: "8.5.14"
  ws: "8.20.1"
