/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFhoxManager__factory } from "./IFhoxManager__factory";
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
