/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace IFhoxManager {
  export type EntityMetadataStruct = {
    legalName: string;
    jurisdiction: string;
    filingId: string;
    articlesHash: BytesLike;
    operatingAgreementHash: BytesLike;
    formedAt: BigNumberish;
  };

  export type EntityMetadataStructOutput = [
    legalName: string,
    jurisdiction: string,
    filingId: string,
    articlesHash: string,
    operatingAgreementHash: string,
    formedAt: bigint
  ] & {
    legalName: string;
    jurisdiction: string;
    filingId: string;
    articlesHash: string;
    operatingAgreementHash: string;
    formedAt: bigint;
  };
}

export interface FhoxFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "form"
      | "identityRegistry"
      | "isNameTaken"
      | "managerByName"
      | "onERC721Received"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FhoxFormed"): EventFragment;

  encodeFunctionData(
    functionFragment: "form",
    values: [
      IFhoxManager.EntityMetadataStruct,
      InEuint128Struct,
      boolean,
      boolean,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isNameTaken", values: [string]): string;
  encodeFunctionData(
    functionFragment: "managerByName",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "form", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNameTaken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managerByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace FhoxFormedEvent {
  export type InputTuple = [
    manager: AddressLike,
    principal: AddressLike,
    identityTokenId: BigNumberish,
    legalName: string,
    jurisdiction: string,
    filingId: string,
    articlesHash: BytesLike,
    operatingAgreementHash: BytesLike
  ];
  export type OutputTuple = [
    manager: string,
    principal: string,
    identityTokenId: bigint,
    legalName: string,
    jurisdiction: string,
    filingId: string,
    articlesHash: string,
    operatingAgreementHash: string
  ];
  export interface OutputObject {
    manager: string;
    principal: string;
    identityTokenId: bigint;
    legalName: string;
    jurisdiction: string;
    filingId: string;
    articlesHash: string;
    operatingAgreementHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhoxFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FhoxFactory;
  waitForDeployment(): Promise<this>;

  interface: FhoxFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  form: TypedContractMethod<
    [
      md: IFhoxManager.EntityMetadataStruct,
      encDailyCap: InEuint128Struct,
      hasDailyCap_: boolean,
      allowlistOnly_: boolean,
      principal_: AddressLike,
      mediator_: AddressLike,
      identityMetadataURI: string
    ],
    [[string, bigint] & { manager: string; identityTokenId: bigint }],
    "nonpayable"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isNameTaken: TypedContractMethod<
    [legalName: string],
    [[boolean, string] & { taken: boolean; existingManager: string }],
    "view"
  >;

  managerByName: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "form"
  ): TypedContractMethod<
    [
      md: IFhoxManager.EntityMetadataStruct,
      encDailyCap: InEuint128Struct,
      hasDailyCap_: boolean,
      allowlistOnly_: boolean,
      principal_: AddressLike,
      mediator_: AddressLike,
      identityMetadataURI: string
    ],
    [[string, bigint] & { manager: string; identityTokenId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isNameTaken"
  ): TypedContractMethod<
    [legalName: string],
    [[boolean, string] & { taken: boolean; existingManager: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "managerByName"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FhoxFormed"
  ): TypedContractEvent<
    FhoxFormedEvent.InputTuple,
    FhoxFormedEvent.OutputTuple,
    FhoxFormedEvent.OutputObject
  >;

  filters: {
    "FhoxFormed(address,address,uint256,string,string,string,bytes32,bytes32)": TypedContractEvent<
      FhoxFormedEvent.InputTuple,
      FhoxFormedEvent.OutputTuple,
      FhoxFormedEvent.OutputObject
    >;
    FhoxFormed: TypedContractEvent<
      FhoxFormedEvent.InputTuple,
      FhoxFormedEvent.OutputTuple,
      FhoxFormedEvent.OutputObject
    >;
  };
}
