/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace IFhoxManager {
  export type EntityMetadataStruct = {
    legalName: string;
    jurisdiction: string;
    filingId: string;
    articlesHash: BytesLike;
    operatingAgreementHash: BytesLike;
    formedAt: BigNumberish;
  };

  export type EntityMetadataStructOutput = [
    legalName: string,
    jurisdiction: string,
    filingId: string,
    articlesHash: string,
    operatingAgreementHash: string,
    formedAt: bigint
  ] & {
    legalName: string;
    jurisdiction: string;
    filingId: string;
    articlesHash: string;
    operatingAgreementHash: string;
    formedAt: bigint;
  };

  export type PolicyViewStruct = {
    hasDailyCap: boolean;
    allowlistOnly: boolean;
  };

  export type PolicyViewStructOutput = [
    hasDailyCap: boolean,
    allowlistOnly: boolean
  ] & { hasDailyCap: boolean; allowlistOnly: boolean };
}

export interface FhoxManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_COOLDOWN"
      | "allowlist"
      | "allowlistOnly"
      | "disputes"
      | "executePayment"
      | "factory"
      | "getSealedDailyCap"
      | "getSealedTodaySpent"
      | "hasDailyCap"
      | "identityTokenId"
      | "initialize"
      | "knownCounterparty"
      | "lastDisputeAt"
      | "mediator"
      | "metadata"
      | "nextDisputeId"
      | "nextPaymentId"
      | "openDispute"
      | "pay"
      | "pendingPayments"
      | "policyView"
      | "principal"
      | "resolveDispute"
      | "rotateMediator"
      | "rotatePrincipal"
      | "setAllowlist"
      | "setPolicy"
      | "treasuryBalance"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowlistUpdated"
      | "DisputeOpened"
      | "DisputeResolved"
      | "Initialized"
      | "MediatorRotated"
      | "PaymentExecuted"
      | "PaymentInitiated"
      | "PolicyUpdated"
      | "PrincipalRotated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowlist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSealedDailyCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSealedTodaySpent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasDailyCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identityTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      IFhoxManager.EntityMetadataStruct,
      InEuint128Struct,
      boolean,
      boolean,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "knownCounterparty",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDisputeAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "mediator", values?: undefined): string;
  encodeFunctionData(functionFragment: "metadata", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextDisputeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [AddressLike, InEuint128Struct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingPayments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyView",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "principal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateMediator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotatePrincipal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowlist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [InEuint128Struct, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowlist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowlistOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSealedDailyCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSealedTodaySpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDailyCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "knownCounterparty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDisputeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mediator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextDisputeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policyView", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "principal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotateMediator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotatePrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AllowlistUpdatedEvent {
  export type InputTuple = [counterparty: AddressLike, allowed: boolean];
  export type OutputTuple = [counterparty: string, allowed: boolean];
  export interface OutputObject {
    counterparty: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    counterparty: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    counterparty: string,
    reason: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    counterparty: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    counterparty: AddressLike,
    awardToCounterparty: BigNumberish,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    disputeId: bigint,
    counterparty: string,
    awardToCounterparty: bigint,
    evidenceHash: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    counterparty: string;
    awardToCounterparty: bigint;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [
    principal: AddressLike,
    mediator: AddressLike,
    identityTokenId: BigNumberish
  ];
  export type OutputTuple = [
    principal: string,
    mediator: string,
    identityTokenId: bigint
  ];
  export interface OutputObject {
    principal: string;
    mediator: string;
    identityTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MediatorRotatedEvent {
  export type InputTuple = [previous: AddressLike, next: AddressLike];
  export type OutputTuple = [previous: string, next: string];
  export interface OutputObject {
    previous: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [counterparty: AddressLike, memoHash: BytesLike];
  export type OutputTuple = [counterparty: string, memoHash: string];
  export interface OutputObject {
    counterparty: string;
    memoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentInitiatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    counterparty: AddressLike,
    memoHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: bigint,
    counterparty: string,
    memoHash: string
  ];
  export interface OutputObject {
    paymentId: bigint;
    counterparty: string;
    memoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyUpdatedEvent {
  export type InputTuple = [hasDailyCap: boolean, allowlistOnly: boolean];
  export type OutputTuple = [hasDailyCap: boolean, allowlistOnly: boolean];
  export interface OutputObject {
    hasDailyCap: boolean;
    allowlistOnly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrincipalRotatedEvent {
  export type InputTuple = [previous: AddressLike, next: AddressLike];
  export type OutputTuple = [previous: string, next: string];
  export interface OutputObject {
    previous: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhoxManager extends BaseContract {
  connect(runner?: ContractRunner | null): FhoxManager;
  waitForDeployment(): Promise<this>;

  interface: FhoxManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  allowlist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  allowlistOnly: TypedContractMethod<[], [boolean], "view">;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        counterparty: string;
        amountAtIssue: bigint;
        status: bigint;
        openedAt: bigint;
      }
    ],
    "view"
  >;

  executePayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  getSealedDailyCap: TypedContractMethod<[], [string], "nonpayable">;

  getSealedTodaySpent: TypedContractMethod<[], [string], "nonpayable">;

  hasDailyCap: TypedContractMethod<[], [boolean], "view">;

  identityTokenId: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      md: IFhoxManager.EntityMetadataStruct,
      encDailyCap: InEuint128Struct,
      hasCap_: boolean,
      allowlistOnly_: boolean,
      principal_: AddressLike,
      mediator_: AddressLike,
      identityTokenId_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  knownCounterparty: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  lastDisputeAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mediator: TypedContractMethod<[], [string], "view">;

  metadata: TypedContractMethod<
    [],
    [IFhoxManager.EntityMetadataStructOutput],
    "view"
  >;

  nextDisputeId: TypedContractMethod<[], [bigint], "view">;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  openDispute: TypedContractMethod<
    [counterparty: AddressLike, amountClaimed: BigNumberish, reason: string],
    [bigint],
    "nonpayable"
  >;

  pay: TypedContractMethod<
    [
      counterparty: AddressLike,
      encAmount: InEuint128Struct,
      memoHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  pendingPayments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        counterparty: string;
        encActualAmountHandle: string;
        memoHash: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  policyView: TypedContractMethod<
    [],
    [IFhoxManager.PolicyViewStructOutput],
    "view"
  >;

  principal: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [
      disputeId: BigNumberish,
      awardToCounterparty: BigNumberish,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rotateMediator: TypedContractMethod<
    [next: AddressLike],
    [void],
    "nonpayable"
  >;

  rotatePrincipal: TypedContractMethod<
    [next: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllowlist: TypedContractMethod<
    [counterparty: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setPolicy: TypedContractMethod<
    [encDailyCap: InEuint128Struct, hasCap_: boolean, allowlistOnly_: boolean],
    [void],
    "nonpayable"
  >;

  treasuryBalance: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowlist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowlistOnly"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        counterparty: string;
        amountAtIssue: bigint;
        status: bigint;
        openedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSealedDailyCap"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getSealedTodaySpent"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "hasDailyCap"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "identityTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      md: IFhoxManager.EntityMetadataStruct,
      encDailyCap: InEuint128Struct,
      hasCap_: boolean,
      allowlistOnly_: boolean,
      principal_: AddressLike,
      mediator_: AddressLike,
      identityTokenId_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "knownCounterparty"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDisputeAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mediator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "metadata"
  ): TypedContractMethod<[], [IFhoxManager.EntityMetadataStructOutput], "view">;
  getFunction(
    nameOrSignature: "nextDisputeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [counterparty: AddressLike, amountClaimed: BigNumberish, reason: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<
    [
      counterparty: AddressLike,
      encAmount: InEuint128Struct,
      memoHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingPayments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        counterparty: string;
        encActualAmountHandle: string;
        memoHash: string;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyView"
  ): TypedContractMethod<[], [IFhoxManager.PolicyViewStructOutput], "view">;
  getFunction(
    nameOrSignature: "principal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      disputeId: BigNumberish,
      awardToCounterparty: BigNumberish,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateMediator"
  ): TypedContractMethod<[next: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rotatePrincipal"
  ): TypedContractMethod<[next: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowlist"
  ): TypedContractMethod<
    [counterparty: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [encDailyCap: InEuint128Struct, hasCap_: boolean, allowlistOnly_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AllowlistUpdated"
  ): TypedContractEvent<
    AllowlistUpdatedEvent.InputTuple,
    AllowlistUpdatedEvent.OutputTuple,
    AllowlistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MediatorRotated"
  ): TypedContractEvent<
    MediatorRotatedEvent.InputTuple,
    MediatorRotatedEvent.OutputTuple,
    MediatorRotatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentInitiated"
  ): TypedContractEvent<
    PaymentInitiatedEvent.InputTuple,
    PaymentInitiatedEvent.OutputTuple,
    PaymentInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyUpdated"
  ): TypedContractEvent<
    PolicyUpdatedEvent.InputTuple,
    PolicyUpdatedEvent.OutputTuple,
    PolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PrincipalRotated"
  ): TypedContractEvent<
    PrincipalRotatedEvent.InputTuple,
    PrincipalRotatedEvent.OutputTuple,
    PrincipalRotatedEvent.OutputObject
  >;

  filters: {
    "AllowlistUpdated(address,bool)": TypedContractEvent<
      AllowlistUpdatedEvent.InputTuple,
      AllowlistUpdatedEvent.OutputTuple,
      AllowlistUpdatedEvent.OutputObject
    >;
    AllowlistUpdated: TypedContractEvent<
      AllowlistUpdatedEvent.InputTuple,
      AllowlistUpdatedEvent.OutputTuple,
      AllowlistUpdatedEvent.OutputObject
    >;

    "DisputeOpened(uint256,address,string)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,uint128,bytes32)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "Initialized(address,address,uint256)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MediatorRotated(address,address)": TypedContractEvent<
      MediatorRotatedEvent.InputTuple,
      MediatorRotatedEvent.OutputTuple,
      MediatorRotatedEvent.OutputObject
    >;
    MediatorRotated: TypedContractEvent<
      MediatorRotatedEvent.InputTuple,
      MediatorRotatedEvent.OutputTuple,
      MediatorRotatedEvent.OutputObject
    >;

    "PaymentExecuted(address,bytes32)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PaymentInitiated(uint256,address,bytes32)": TypedContractEvent<
      PaymentInitiatedEvent.InputTuple,
      PaymentInitiatedEvent.OutputTuple,
      PaymentInitiatedEvent.OutputObject
    >;
    PaymentInitiated: TypedContractEvent<
      PaymentInitiatedEvent.InputTuple,
      PaymentInitiatedEvent.OutputTuple,
      PaymentInitiatedEvent.OutputObject
    >;

    "PolicyUpdated(bool,bool)": TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;
    PolicyUpdated: TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;

    "PrincipalRotated(address,address)": TypedContractEvent<
      PrincipalRotatedEvent.InputTuple,
      PrincipalRotatedEvent.OutputTuple,
      PrincipalRotatedEvent.OutputObject
    >;
    PrincipalRotated: TypedContractEvent<
      PrincipalRotatedEvent.InputTuple,
      PrincipalRotatedEvent.OutputTuple,
      PrincipalRotatedEvent.OutputObject
    >;
  };
}
