/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockIdentityRegistry } from "./MockIdentityRegistry";
export type { MockUSDC } from "./MockUSDC";
