/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockIdentityRegistry__factory } from "./MockIdentityRegistry__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
