/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFhoxManager } from "./IFhoxManager";
export type { IIdentityRegistry } from "./IIdentityRegistry";
